version: '2'
services:
  web:
    image: tutum/hello-world:latest
    ports:
      - "8081:80"

  nginx:
    build: .
    ports:
      - 8080:80
      - 8090:8090
    environment:
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
      - PROXY_PASS=http://web/
